Update ci.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,4 +29,7 @@ jobs:
         run: ls -la dist/
 
       - name: Verify Main File Exists
-        run: test -f dist/index.js || (echo "Error: dist/index.js not found" && exit 1)
+        run: test -f dist/index.js
+      - name: Fail if Main File is Missing
+        if: failure()
+        run: 'echo "Error: dist/index.js not found" && exit 1'
